config:
  log_path: ~/.dabcup/dabcup.log            # Default value
  log_level: error                          # debug, info, warn, error, fatal (default error)
  log_age: 9                                # number (default 0)
  log_size: 5                               # Size of each log file (in MB) (default 5)
  log_datetime_format: '[%Y-%m-%d %H:%M]'   # See http://www.ruby-doc.org/core/classes/Time.html#M000297